name: Docker Build and Push

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_USERNAME }}/outreach-composer-for-job-search:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_IMAGE_USERNAME }}/outreach-composer-for-job-search:${{ github.sha }} ${{ secrets.DOCKER_IMAGE_USERNAME }}/outreach-composer-for-job-search:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/outreach-composer-for-job-search:${{ github.sha }}
        docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/outreach-composer-for-job-search:latest
