name: Docker Build and Push

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and tag Docker image
      run: |
        docker build -t ghcr.io/${{ github.actor }}/cold-connect:${{ github.sha }} .
        docker tag ${{ github.actor }}/cold-connect:${{ github.sha }} ${{ github.actor }}/cold-connect:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.actor }}/cold-connect:${{ github.sha }}
        docker push ghcr.io/${{ github.actor }}/cold-connect:latest
